### ISSUE TITLE
webrtc signaling

### ISSUE THREAD

**Issue by substack** [substack/peernet#2]
Here's how using what peernet can already do can be used to perform p2p webrtc signaling (and thereby boosting the reach of peernet into any webrtc-capable browser).

A browser peer called X wants to talk to other webrtc peers and is already connected to one or more peernet websocket services. X should then join the `webrtc-signal` subnet. When X gets an incoming search for `webrtc-signal`, it should generate a new webrtc signal and listen on a new subnet that is the hash of the signal data.

When another browser peer, Y, wants to connect to another peer over webrtc, it first searches for peers on the `webrtc-signal` subnet. Y then publishes a search reply message to X with its own signal in the response payload.

This technique might require storing the sequence for X's search someplace, or being lenient with sequences on X's side.

**Comment by substack** [comment]
There's now a basic implementation in the v2 branch, but wrtc keeps segfaulting.

**Comment by substack** [comment]
I've just got webrtc discovery working in real browsers.

**Comment by substack** [comment]
This is in v2, it's just fickle and buggy.

**Comment by RangerMauve** [comment]
Do you have a description of how you're doing the signaling somewhere, or would it be better to just read the source? My reasoning is that it'd be nice if there was some standard way for people to do signaling across different projects out there.
